name: linting, testing, building
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches:
      - master
  pull_request: 
    branches:
      - master
jobs:
  linting-testing-building:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Install modules
        run: npm install
      - name: eslint
        run: npm run lint
      - name: stylelint
        run: npm run lint:scss
      - name: unit testing
        run: npm run test:unit
      - name: build production
        run: npm run build:prod
